services:
  - type: web
    name: next-js
    runtime: node
    plan: free
    buildCommand: pnpm install; pnpm build
    startCommand: pnpm start
    autoDeploy: false
    envVars:
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_HOST_API
        value: "https://flowup-nestjs-api.onrender.com"
      - key: NEXT_PUBLIC_ASSETS_API
        value: "https://flowup-nestjs-api.onrender.com/"